### ISSUE TITLE
BadValue nojournal is not allowed when configsvr is specified

### ISSUE THREAD

**Issue by pokkie** [flapdoodle-oss/de.flapdoodle.embed.mongo#199]
I am following the instructions here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#import-json-file-with-mongoimport-command

When I try to run the test case, I get the following stacktrace:

01:19:23.044 [main] DEBUG de.flapdoodle.embed.process.runtime.ProcessControl - Detected pid: 3522
01:19:23.046 [main] DEBUG de.flapdoodle.embed.process.runtime.ProcessControl - Detected pid: 3524
[mongod output]2017-02-03T01:19:23.057+0200 F CONTROL  [main] Failed global initialization: **BadValue nojournal is not allowed when configsvr is specified**
[mongod output] 
01:19:23.061 [main] ERROR de.flapdoodle.embed.process.runtime.AbstractProcess - failed to call onAfterProcessStart()
java.io.IOException: Could not start process: <EOF>

Any ideas as to how to fix it?

**Comment by michaelmosmann** [comment]
Hmm.. tests works, so maybe i must update the documentation.

**Comment by Loki-Afro** [comment]
@michaelmosmann is the resolved somehow?

**Comment by luisfilipe46** [comment]
Hello @michaelmosmann,

Thank you for make flapdoodle.embed.mongo. It's been really useful for me!

I'm trying to set up Mongod, Mongos and config server but I'm having the same error message of @pokkie . I followed your code example: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#start-mongos-with-mongod-instance

The problem is on start function call inside the startMongod function.
I noticed that when I don't use the configserver in mongod, the code doesn't crash.
Do I have to set up a config server before initialize a mongod ? Is there any type of configuration needed to set up a config server in startMongod function? Am I doing something wrong ? Is there any alternative way?

Thank you in advance !

**Comment by michaelmosmann** [comment]
I am not sure why there is so much trouble with mongos etc.. it should 
work,but it didn't.. maybe someone should port a working setup into some 
kind of testable code.. but currently I do not have enough time for this.

Sorry...



Am 16. Mai 2017 7:09:29 nachm. schrieb Luis Araújo <notifications@github.com>:

**Comment by luisfilipe46** [comment]
Since I didn't find any solution, I tried to use MongosSystemForTestFactory and I had the same issue/error message.

After searching a while for a solution, I think that the problem should be on MongoDB.
I found this issue which is unsolved until now: https://jira.mongodb.org/browse/SERVER-24551.

Now I'm using Version.Main.V3_0 in MongosSystemForTestFactory and it's working as expected now !

**Comment by Loki-Afro** [comment]
@luisfilipe46 thanks for providing the solution, closing this :)
