### ISSUE TITLE
Server is not stopped when JVM ends. 

### ISSUE THREAD

**Issue by popkutty** [flapdoodle-oss/de.flapdoodle.embed.mongo#201]
I have  a test which running in a builder. I'm starting embedded DB for my test. If the test got stopped in between like if the build is stopped, then unit test jvm ends but that's not stopping the server. I did tear down in test to stop server. But somehow my test failed to reach tear down then it will be an issue. Any workaround for this?

**Comment by Loki-Afro** [comment]
Can you provide the source code?

**Comment by Loki-Afro** [comment]
Anyway, If build is stopped means sending a SIGTERM to the JVM process and you implemented the test correctly, e.g. using the `@After` annotation for example the current test will end and the code in `after` gets executed which could be something like
```
    @After
    protected void after() {
        mongod.stop();
        mongodExe.stop();
    }
```

The following pseudocode won't work in all cases and could leave a zombie process
```
@Test
public fancyTest(){
MongodProcess mongo = startMongoSomehow();
doFancyDbStuff();
XXX SIGTERM XXX
mongo.stop();
}
```

When sending a SIGKILL to the JVM the mongo process will stay alive,simply because its another process.

No clue what on Windows happens.

**Comment by michaelmosmann** [comment]
It is even harder in windows to kill a mongo process.. IMHO if the jvm process dies on linux the mongo process could die with it. But not on windows.. thats why we have some special code which tries to kill the mongo instance on windows.
