### ISSUE TITLE
We couldn't kill mongod process, and tried a lot.

### ISSUE THREAD

**Issue by dazraf** [flapdoodle-oss/de.flapdoodle.embed.mongo#268]
Here are the details - please ask me if there's more information that's required, thanks:

With libraries:

```
embed.mongo: 2.1.1
embed.process: 2.0.5
```

On Ubuntu server:
```
uname -a
Linux etb3 4.15.0-1035-azure #36~16.04.1-Ubuntu SMP Fri Nov 30 15:25:49 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

with ulimits:

```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 64083
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 64083
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Build log:

```
[mongod output] 2018-12-07T11:25:36.639+0000 I NETWORK  [conn2] end connection 127.0.0.1:58080 (0 connections now open)
[mongod output] 2018-12-07 11:25:36,650 INFO    i.c.networkmap.storage.EmbeddedMongo - manual shutdown in progress
2018-12-07T11:25:36.651+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:58104 #3 (1 connection now open)
[mongod output] 2018-12-07 11:25:36,655 ERROR   d.f.embed.mongo.runtime.Mongod - Got some response, should be an error message
2018-12-07T11:25:36.655+0000 I NETWORK  [conn3] end connection 127.0.0.1:58104 (0 connections now open)
[mongod output] 2018-12-07 11:25:36,755 WARN    d.f.embed.mongo.AbstractMongoProcess - could not stop mongod with db command, try next

2018-12-07T11:25:36.758+0000 I CONTROL  [signalProcessingThread] got signal 2 (Interrupt), will terminate after current cmd ends
[mongod output] 2018-12-07T11:25:36.758+0000 I NETWORK  [signalProcessingThread] shutdown: going to close listening sockets...
[mongod output] 2018-12-07T11:25:36.758+0000 I NETWORK  [signalProcessingThread] removing socket file: /tmp/mongodb-44059.sock
[mongod output] 2018-12-07T11:25:36.758+0000 I FTDC     [signalProcessingThread] Shutting down full-time diagnostic data capture
[mongod output] 2018-12-07T11:25:36.760+0000 I STORAGE  [signalProcessingThread] WiredTigerKVEngine shutting down
[mongod output] Exception in thread "vert.x-eventloop-thread-8" java.lang.IllegalStateException: Couldn't kill mongod process!

----------------------------------------------------
Something bad happend. We couldn't kill mongod process, and tried a lot.
If you want this problem solved you can help us if you open a new issue.

Follow this link:
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues

Thank you:)
----------------------------------------------------
```

**Comment by Loki-Afro** [comment]
Is this reproduceable?
Got the process killed afterwords by its own?
If not did you try to just kill it (without force ;))? - what happened?

**Comment by dazraf** [comment]
Some more background:
We have a about 20 tests that are executed sequentially using maven;both on our local laptops (lmacbook pro 2018 with latest OS X) and our build servers (Ubuntu). Each creates a mongod instance; sets up users using mongo shell; then waits for a shutdown, before restarting the mongod with auth mode enabled. 

The linux webservers has been configured with the ulimit hard values as requested by the mongodb documentation. 

On local laptops this works fine every time. On the build servers we see two issues:
1. very rarely, the issue described here
2. very often, a stdout pipe error that stops flapdoodle seeing the mongod output log, causing it to hang.

Since raising this issue, I have changed our tests to use a single shared mongod instance, with salted database names. This has eliminated the issues I noted above. 

I wonder if there are recommendations here on the best way to setup tests with flapdoodle to get consistently good behaviour on various kit. Thanks.

**Comment by ptempes** [comment]
I have a similar issue. I am using mongo server process configured to be replicaset in some of my tests and I ger the same error. Interesting fact is that when I put a breakpoint and wait a bit for `Integer retCode=stopOrDestroyProcess();` then the value is not null but 0 and no error appears.

**Comment by Loki-Afro** [comment]
@ptempes sounds like a timing problem to be, I'm not on my laptop now but i guess there was a parameter where you could modify that

@dazraf sorry for the late reply!
We or at least I never heard of such an issue but could also be related to the "stopOrDestroyProcess" - timeout

> then waits for a shutdown
How do you accomplish that? Your setup sounds very complex ;)

**Comment by shollander** [comment]
I am having the exact same issue as @ptempes.

We configure embedmongo to use a replicaset (single server) in order to test transactional methods with mongodb 4.0. We are doing it similar to this https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/issues/257#issuecomment-407770356

Almost every time we encounter this error message on shutdown.

The `extractmongod` process does go away almost immediately after the error message appears, so perhaps this is a timing issue. I can get the error message to go away by increasing the `stopTimeoutInMillis()` setting on `MongoConfigBuilder`. Increasing it by one second (six seconds instead of the default of five seconds) is enough for us.

I am wondering though, why does it take so long to shutdown when using the single node replica set? Perhaps there is something else that needs to be done in order to shutdown the replicaset cleanly?

**Comment by shollander** [comment]
I've been doing some more digging and I wonder if this is the problem..

I see that embed mongo tries to shutdown the database by issuing a shutdown command over the network port. 

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/7ccd324bde3823eca6f4cc8a1096c57d91fd4bbe/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L61-L91

I am not sure what that binary command actually consists of, but I did notice the following in the mongoDB manual for the [shutdown command](https://docs.mongodb.com/manual/reference/command/shutdown/)

> If the node you’re trying to shut down is a replica set primary, then the command will succeed only if there exists a secondary node whose oplog data is within 10 seconds of the primary. You can override this protection using the force option

Does the binary shutdown command used by `Mongod.sendShutdown()` include the `force` option? If it does not, that would explain the behavior I am seeing. The shutdown command is not working, and the mongo process only dies when `process.destroy()` is called (`ProcessControl.stopOrDestroyProcess()`).

If that is the case then perhaps the `force` option can be added to the default, or give users the option to use `force` when attempting to shut down the embedmongo process.

**Comment by shollander** [comment]
Looking a little more at this issue, it looks like the current `SHUTDOWN_COMMAND` bytes *does* include the `force` option. I don't fully understand the format of the bytes, but the sequence
```
0x66, 0x6F, 0x72, 0x63, 0x65
```
is equal to "force" in ASCII.

I think the actual problem is that the command is missing the `timeoutSecs` option (see [shutdown command](https://docs.mongodb.com/manual/reference/command/shutdown/)). I experimented using the mongo shell, and without the `timeoutSecs` option the command took a while to complete. If I added `timeoutSecs: 0` then the database would shut down instantly.

I couldn't figure out how to add the `timeoutSecs` option to the `SHUTDOWN_COMMAND` bytes though.

**Comment by shollander** [comment]
Doing a little research into the mongodb wire format, I figured out how to add the `timeoutSecs: 0` option. 
Changing `SHUTDOWN_COMMAND` to the following fixes the issue for me:
```
 	static final byte[] SHUTDOWN_COMMAND = { 0x58, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
 			(byte) 0xD4, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x61, 0x64, 0x6D, 0x69, 0x6E, 0x2E, 0x24, 0x63, 0x6D, 
 			0x64, 0x00, 0x00, 0x00, 0x00, 0x00, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, (byte) 0xFF, 0x2C, 0x00, 0x00, 
 			0x00, 0x10, 0x73, 0x68, 0x75, 0x74, 0x64, 0x6F, 0x77, 0x6E, 0x00, 0x01, 0x00, 0x00, 0x00, 0x08, 0x66, 0x6F, 
 			0x72, 0x63, 0x65, 0x00, 0x01, 0x10, 0x74, 0x69, 0x6D, 0x65, 0x6F, 0x75, 0x74, 0x53, 0x65, 0x63, 0x73, 0x00, 
                        0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00 }; 
```

**Comment by shollander** [comment]
@Loki-Afro I submitted  pull request #299 to fix the issue with replicaset shutdown that @ptempes and I have been having.

**Comment by shilpauran** [comment]
its because the process takes a few seconds to shutdown. so do an await for a few seconds and then let the process stop. below is the java code for the same. keep in mind that process and executable are already created. this is just to stop the mongoDb
import static org.awaitility.Awaitility.await;
	public void stopMongoDb() throws IOException {
		if (process != null) {
			try {
				process.stop();
			} catch (IllegalStateException e) {
				if (process != null) {
					await().atMost(1, TimeUnit.MINUTES).until(() -> !process.isProcessRunning());
				} else {
					throw new IllegalStateException(e);
				}
			}
		}
		if (mongodExecutable != null) {
			mongodExecutable.stop();
		}
	}

in the above code, if the process is still running then the method isProcessRunning() returns true. we wait until it is false, or we wait until 1 min is over.

**Comment by michaelmosmann** [comment]
.. reopen if this still is an issue.
