### ISSUE TITLE
403 on Download of Mongo 4.4.1 

### ISSUE THREAD

**Issue by trailoff** [flapdoodle-oss/de.flapdoodle.embed.mongo#327]
Hello :) 
I am using de.flapdoodle.embed.mongo 3.0.0 and here is my code : 

```
    RuntimeConfig runtimeConfig = Defaults
        .runtimeConfigFor(command)
        .artifactStore(Defaults.extractedArtifactStoreFor(command)
            .withDownloadConfig(Defaults.downloadConfigFor(command).build())
            .executableNaming(new UserTempNaming())).build();

    EnumSet<Feature> features = Version.V4_4_1.getFeatures();
    IFeatureAwareVersion iFeatureAwareVersion = Versions.withFeatures(Version.V4_4_1, features);

    ImmutableMongodConfig mongodConfig = ImmutableMongodConfig.builder()
        .version(iFeatureAwareVersion)
        .net(new Net(port, true))
        .build();

    MongodStarter runtime = MongodStarter.getInstance(runtimeConfig);
```

But I get : 
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.4.1.tgz
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at de.flapdoodle.embed.process.store.UrlConnectionDownloader.downloadInputStream(UrlConnectionDownloader.java:130)
	... 30 more

However, If I switch  the version to 4.0.12 for example everything seems fine ... 

Can you please help ? :)

**Comment by robin850** [comment]
It looks like MongoDB changed all their URL patterns for download (since 4.2 IIUC looking at [this page](https://www.mongodb.com/download-center/community/releases/archive) ; and that would explain why it works for you on 4.0.12).

This means that:

* On macOS, the `osx` becomes `macos` only in the archive name (the folder name remains `osx`).
* There seems to be no "generic Linux" package after 4.0, only distro-specific ones.
* The `ssl` part seem to be removed from packages.
* The `2008plus` part is replaced with `2012plus` for Windows archives.
* [Since 3.4](https://docs.mongodb.com/manual/installation/#supported-platforms), there seems to be no support for 32-bit platforms.

Waiting for a fix, you can try something like:

~~~java
class CustomPackageResolver extends Paths {
    public CustomPackageResolver(Command command) {
        super(command);
    }

    @Override
    public String getPath(Distribution distribution) {
        return "linux/mongodb-linux-x86_64-ubuntu1804-4.2.0.tgz";
    }
}
~~~

And then use it like:

~~~java
Command command = Command.MongoD;

RuntimeConfig runtimeConfig Defaults.runtimeConfigFor(command)
        .artifactStore(Defaults.extractedArtifactStoreFor(command)
                .withDownloadConfig(Defaults.downloadConfigFor(command)
                        .packageResolver(new CustomPackageResolver(command))
                        .build()))
        .build();
~~~

(Here is [an attempt](https://gist.github.com/robin850/c6fcbf0378ca04e599e933e562bb6fbf) to have something that works on all OSes but I've only tested it on macOS to be honest.)

Since this project recently bumped to version 3, a lot of versions were deprecated. Maybe, to ease the maintenance, they should be removed because it may be a PITA to provide something that works with older and newer versions.

**Comment by Kobee1203** [comment]
To complete the @robin850 's comment:
* on Windows, the `win32` becomes `windows` in the filename and the folder name since 4.4.x

**Comment by Xaseron** [comment]
No only have they changed the filename structure of the zip file.
Also they have changed the directory name after extraction in a non coherent fashion.

I've already changed this for run-rs https://github.com/vkarpov15/run-rs/blob/master/src/download.js#L57

**Comment by JSONCODE007** [comment]
Any update on this issue?

**Comment by michaelmosmann** [comment]
I did a mayor refactoring to catch this change.. there is a new release.. please try:)
