### ISSUE TITLE
Version 3.4.1 breaks with spring's autoconfig

### ISSUE THREAD

**Issue by bernermic** [flapdoodle-oss/de.flapdoodle.embed.mongo#378]
Hi @michaelmosmann,

with the current version 3.4.1 spring autoconfig breaks.

Springs EmbeddedMongoAutoConfiguration is missing change for deleted class https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/46eeb152b1e69a644627cd7f334c466b9f9e294b/src/main/java/de/flapdoodle/embed/mongo/distribution/Feature.java

in here: https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java#L35

Do you have some experience on the best way to go forward here?

Greetings

**Comment by alabotski** [comment]
Hi I have the same error 
On 3.3.1 all working well

**Comment by michaelmosmann** [comment]
Hmm.. did a little change regarding this but did not expect that.. have to investigate this..

**Comment by michaelmosmann** [comment]
.. oh, i see whats going on.. hmm.. stay with 3.3.x so far..

**Comment by michaelmosmann** [comment]
3.4.0 may also work.. i see if i can create some workaround for this issue

**Comment by michaelmosmann** [comment]
@bernermic hmm.. this error message is strange.. i did restore the de.flapdoodle.embed.mongo.distribution.Feature class (which is now of no use, just to satisfy the runtime) ..

spring team: i can try..

**Comment by bernermic** [comment]
Oh - I made a misstake here. Wrong terminal ...

I'll create a simple testexample and paste the link vor test here.

This is the correct error:
`Error creating bean with name 'embeddedMongoRuntimeConfig' defined in class path resource [org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration$RuntimeConfigConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.flapdoodle.embed.process.config.RuntimeConfig]: Factory method 'embeddedMongoRuntimeConfig' threw exception; nested exception is java.lang.NoClassDefFoundError: de/flapdoodle/embed/mongo/Command`

**Comment by michaelmosmann** [comment]
@bernermic  oh.. fuu.. yes.. moved this to..hmm..

**Comment by michaelmosmann** [comment]
@bernermic hmm.. it would be a lot easier if i would provide more spring integration stuff.. i tried to avoid any additional work.. hmm..

**Comment by bernermic** [comment]
Here I have a working example for testing the spring integration: https://github.com/bernermic/flappdoodleExampletest

This uses `spring-boot-starter-parent:2.6.3` with `de.flapdoodle.embed.mongo:3.4.2`

**Comment by michaelmosmann** [comment]
@bernermic thanks.. i will try to see if i can fix this..

**Comment by bernermic** [comment]
Thanks @michaelmosmann  - if I can support further let me know.

**Comment by snicoll** [comment]
@michaelmosmann `Versions.withFactures` with a version and a set of features has been deprecated with no obvious replacement in the latest release. Spring Boot [uses this method](https://github.com/spring-projects/spring-boot/blob/5454e2e26add471fc879f7641794e9e747a9bdda/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/embedded/EmbeddedMongoAutoConfiguration.java#L157-L158). What should we do?

**Comment by michaelmosmann** [comment]
@snicoll please use version 3.4.2 where i restored most of the functions so only minor changes have to be made.
some background: i changed the "feature"-detection and moved this stuff into a different repo (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/)  (big refactoring ahead, try to reduce merge conflicts, features are now based on version ranges) ..

**Comment by michaelmosmann** [comment]
@snicoll maybe i should start to provide the spring integration stuff myself so that, if i need to change anything can fix this right ahead .. (and there are big changes coming)

**Comment by snicoll** [comment]
@michaelmosmann Thanks but that doesn't answer my concern. How do I update the method I've highlighted so that it doesn't use a deprecated method?

**Comment by michaelmosmann** [comment]
@snicoll is there a branch on which i can create an pull request?

**Comment by snicoll** [comment]
@michaelmosmann I am doing things locally so I'd rather do it myself please.

**Comment by michaelmosmann** [comment]
@snicoll this should work:

```java
    private IFeatureAwareVersion determineVersion(EmbeddedMongoProperties embeddedProperties) {
        Assert.state(embeddedProperties.getVersion() != null, "Set the spring.mongodb.embedded.version property or "
          + "define your own MongodConfig bean to use embedded MongoDB");
        return Versions.withFeatures(createEmbeddedMongoVersion(embeddedProperties));
    }

```

**Comment by snicoll** [comment]
Thanks but the method I've highlighted takes a version and a  set of Features (see `embeddedProperties.getFeatures()`).

**Comment by snicoll** [comment]
https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/032c3c6921ccc288c5ca1c9b4960f390a0a2042f/src/main/java/de/flapdoodle/embed/mongo/distribution/Versions.java#L50-L52 this is called `withFeatures` but doesn't take any.

**Comment by michaelmosmann** [comment]
@snicoll  the feature detection is done inside GenericFeatureAwareVersion .. i tried to make as less changes as possible. If you like you can just call new GenericFeatureAwareVersion(..)

**Comment by snicoll** [comment]
>  i tried to make as less changes as possible. 

As far as we can see, even if we use the deprecated API, the features that we pass in will be ignored. It looks like support for specifying certain features has been removed. This is a major breaking change for what our auto-configuration is doing.

**Comment by michaelmosmann** [comment]
@snicoll no features are removed .. the class moved to an different package (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/main/java/de/flapdoodle/embed/mongo/packageresolver/Feature.java). I did restore the Feature class without any values to reduce compile errors in other projects (which was not enough for spring boot (Comand was also moved).

btw: this is how you will get the features of an version: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/main/java/de/flapdoodle/embed/mongo/packageresolver/DefaultFeatureSetResolver.java

**Comment by michaelmosmann** [comment]
@snicoll and you could not specify any feature .. i tried to reflect the features of the database depending on the version .. which results more or less in different comand line arguments.. so you can not enable or disable a database feature .. is more an description of which feature is present in which database version and is in any way relevant for starting it up (f.i. command line arguments)

**Comment by wilkinsona** [comment]
> you could not specify any feature .. i tried to reflect the features of the database depending on the version

That's a breaking change from Boot's perspective. We relied on the old API to allow users to specify the specific features that they wanted to use. It appears that it's now only possible to use whatever features are considered to be the defaults for a particular version of Mongo.

**Comment by michaelmosmann** [comment]
@wilkinsona maybe we are on a wrong track here.. let me try to explain it a little bit more...

the class https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/main/java/de/flapdoodle/embed/mongo/packageresolver/Feature.java (moved there from this repo) reflects some aspect of mongodb which are relevant if you want to start the mongodb server process. If you provide comand line arguments which are not provided, the start will fail .. here is how the features are come to play:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L125

(or on an refactoring branch: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/refactor/process-graph/src/main/java/de/flapdoodle/embed/mongo/commands/MongodArguments.java)

So the best thing what will happen with any user provided Feature-Set is nothing, the worst: the server does not start. You can not enable something whats not already there .. its more or less only a "config object to command line argument mapping filter".

.. and even when this whould not be the case: i could not find any code inside these spring boot classes which are trying to enable/disable some of these features.. so its an API break..yes.. sorry for that, but its not an behavior change.

**Comment by michaelmosmann** [comment]
@bernermic thanks for your repo .. i use this as a starting point for an canary repo to see if an change breaks any spring boot compat. .. and in the long run i think i will provide the spring integration myself .. this will be much less pain for me.. and maybe for others too.

**Comment by wilkinsona** [comment]
@michaelmosmann The problem that we have is that it no longer appears to be possible for a user to provide a feature set as any features passed into `GenericFeatureAwareVersion` are ignored:

https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/032c3c6921ccc288c5ca1c9b4960f390a0a2042f/src/main/java/de/flapdoodle/embed/mongo/distribution/Versions.java#L60-L70

With 3.4.2, how can we create a feature-aware version with a custom feature set?

**Comment by michaelmosmann** [comment]
@wilkinsona why do you think you have to provide a feature set by your own? what do you expect to customize this way? I do not expect any use who want to provide any custom set for that and.. to have any use of this as its tied to a specific mongodb version.. if you provide a custom feature set, maybe some different command line arguments will be generated based on the mongodb config object and .. mongodb will fail because this command line argument is unknown to this specific mongodb executable...

**Comment by snicoll** [comment]
> why do you think you have to provide a feature set by your own?

@michaelmosmann this is the wrong discussion to have. We are integrating this project, we are not MongoDB experts. Please take the report as it is described. 

In  [`3.4.0`](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/16e63a0d907f713a87bb7c6c826879c7cde0159a/src/main/java/de/flapdoodle/embed/mongo/distribution/Versions.java#L33-L39), there is an API in `Versions` that lets you provide a `Version` and some optional `Feature` instances. There is nothing in that API that indicates that it shouldn't be called, or that it is deprecated. In fact, that's the only methods you can invoke on that class!

In `3.4.1`, the `Feature` class has moved to a different package. This was a breaking change so you released `3.4.2` to make sure that things remain compatible.

In [`3.4.2`](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/032c3c6921ccc288c5ca1c9b4960f390a0a2042f/src/main/java/de/flapdoodle/embed/mongo/distribution/Versions.java) the only methods that were there are `@Deprecated` with no obvious replacement. That is also a breaking change.

I trust your judgment that providing a version and a set of features is wrong and should not be supported but that's not how I expect the transition to happen. What, as integration of this API, are we supposed to do?

**Comment by michaelmosmann** [comment]
@snicoll ok, I understand. What you should do is the method call I mentioned. The other methods where only workarounds .. and will be delete soon.. I created an canary repo to see if any change will break spring autoconfig bevor i make an release.

**Comment by snicoll** [comment]
There is a `spring.mongodb.embedded.features` property that users can define to set the `Feature`s they want. Anybody relying on that will be broken which is what we're trying to say from the start.

Again, it may have been wrong to expose that but nothing in the `3.4.0` API indicates that it should not be done (Those are the only available methods on `Versions`, how were we supposed to know?).

**Comment by michaelmosmann** [comment]
@snicoll I did not know that this property existed .. but it was never intended to be used. And if anyone did use this, I would expect that this would lead to failing mongodb server starts. So in the end the only thing the user has to configure is the mongodb version number.

**Comment by wilkinsona** [comment]
We have tests that verify that it works so I'm not sure why you would expect it to cause Mongo to fail to start.

For example, a user could set `spring.mongodb.embedded.features` to `ONLY_WITH_SSL`. This starts Mongo 3.5.5 with the following command line:

```
[/var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/extract-a074c29d-7471-40c7-b60f-56176f3aa87fextractmongod, --dbpath, /var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/embedmongo-db-02858612-1c04-4f94-be1a-625969a1ff14, --noauth, --noprealloc, --smallfiles, --nojournal, --nohttpinterface, --port, 52194, --bind_ip, 127.0.0.1]
```

By contrast, the default command line for 3.5.5 is the following:

```
[/var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/extract-8b36c585-a1a6-46d1-9746-18205d310c4eextractmongod, --dbpath, /var/folders/2w/mhq2nt4d0xx2w6w4c36n468h0000gn/T/embedmongo-db-578eaee9-7e8c-46ee-b18c-3fb439a040d8, --noauth, --noprealloc, --smallfiles, --nojournal, --nohttpinterface, --port, 52091, --bind_ip, 127.0.0.1, --syncdelay=0]
```

Note that the `--syncdelay` option is only present in the latter. Mongo starts successfully in both cases. As you know, the `ONLY_WITH_SSL` option also allows the user to influence the distribution that's downloaded.

**Comment by michaelmosmann** [comment]
@wilkinsona ONLY_WITH_SSL was there as some indicator that some mongodb versions for windows contained an "-ssl-" in the download path .. which is gone since i had to rewrite this part because mongodb changed from generic download url scheme to a version and platform specific packed scheme.

So with providing some value to `spring.mongodb.embedded.features` the value `SYNC_DELAY` was not set, so the command line did not contain `--syncdelay=0` (see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/master/src/main/java/de/flapdoodle/embed/mongo/runtime/Mongod.java#L196). This does not have anything to do with any ssl feature of the mongodb server.

That mongodb did not fail to start: version 3.5.5 does understand the most command line arguments.. if you want to try to see it break you should try NO_HTTP_INTERFACE_ARG. The command line should then contain `--nohttpinterface` which is supported with mongodb >= 3.6.x .. so this time the start should fail.

**Comment by michaelmosmann** [comment]
@wilkinsona Feel free to ask questions, if you don't understand everything in this project.. it's old, it is complicated (that's why there is a big refactoring going on) .. and i will change the code if i can make things easier.. but i will only make it better, not wrong again.

**Comment by michaelmosmann** [comment]
@bernermic did a new release 3.4.3 .. with some minor hacks it works again:) so please try ..

**Comment by michaelmosmann** [comment]
@wilkinsona @snicoll fixed the last api mismatch as far as this simple test will catch any issue (https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary) .. so it should work again without any change.. but feel free to clean up some edges:)

**Comment by michaelmosmann** [comment]
@bernermic the canary project helped a lot :) ( https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.canary )

**Comment by bernermic** [comment]
@michaelmosmann thanks for your work on this. Version 3.4.3 is rolled out and works fine with spring-boot-starter-parent:2.6.4

And glad that the testrepo helped :)

**Comment by wilkinsona** [comment]
> ONLY_WITH_SSL was there as some indicator that some mongodb versions for windows contained an "-ssl-" in the download path

Yeah, I understand that. I used it in my example to demonstrate the utility of creating a version with a custom feature set. I find the removal of that capability in a 3.4.x release surprising.

> the value `SYNC_DELAY` was not set, so the command line did not contain `--syncdelay=0`

Exactly. By ignoring the features that are passed in when creating a feature-aware version, this capability has been lost. 

> That mongodb did not fail to start: version 3.5.5 does understand the most command line arguments

Hopefully I've demonstrated that if as user understands the capabilities of the version of Mongo that they are using then they can safely use a custom feature set to control its behaviour. I see this as being the same as a user having to understand the command line arguments that a particular version of Mongo supports if they were launching it manually.

It sounds like we'll need to adjust Spring Boot to cope with support for a custom feature set being removed. We can do that, of course, but it's a surprising adjustment to have to make when upgrading from one 3.4.x release to another 3.4.x release.

We'll remove support for configuring a custom feature set in Spring Boot 2.7.

**Comment by michaelmosmann** [comment]
> Yeah, I understand that. I used it in my example to demonstrate the utility of creating a version with a custom feature set. I find the removal of that capability in a 3.4.x release surprising.

as a user you can configure how the mongodb server behaves with setting the matching attributes in the MongodConfig class.. which will be translated to command line arguments IF the current mongodb does support this... just providing a user selected feature set will at best give you the same result, but can render any attribute in MongdConfig useless, at worst will fail to start the server. So it's not a capability which is intended to be used for any customization, and it was not really an part of the public api.. more an bad workaround of some wrong generalisations.

> > That mongodb did not fail to start: version 3.5.5 does understand the most command line arguments
> 
> Hopefully I've demonstrated that if a user understands the capabilities of the version of Mongo that they are using then they can safely use a custom feature set to control its behaviour. I see this as being the same as a user having to understand the command line arguments that a particular version of Mongo supports if they were launching it manually.

Then i must make this more clear in the feature that this is not the way it works.. sorry for this misunderstanding.

> It sounds like we'll need to adjust Spring Boot to cope with support for a custom feature set being removed. We can do that, of course, but it's a surprising adjustment to have to make when upgrading from one 3.4.x release to another 3.4.x release.

Until now i did not had any checks for any spring integration (now i have).. i tried in the past to reduce this kind of impact because i know that many people are using my project with very different spring versions .. but this time i failed and tried to make it work again (which it does with the last release).

> We'll remove support for configuring a custom feature set in Spring Boot 2.7.

Yes.. you should.

**Comment by michaelmosmann** [comment]
@wilkinsona 
Some final notes: I do this project in my spare time. I did this just for myself and over the time other developers found it useful to them. Then some day I learned about the spring integration by surprise. So it is maybe not that bad at all. 

But i can not remember any pull request or some support from spring, or questions if something is not clear .. it is just used as a useful tool, integrated into the spring stack, ready to use if everything is running well. I remember some issues where i had to fix some spring integration issues, and i am willing to give support to other developers out there, because this is beside all the effort the rewarding part of this game.

But maybe you have to accept that it is not any kind of rewarding, that i have to discuss my decisions with someone who insist using my stuff in a certain way. In the last days i thought about why i am doing this a lot. If the stats are somehow reliable then each month around 100.000 users are using this project somehow .. i am doing this for them. And if it does not work for them i see this because there are new issues which a try to solve. And i feel my work valued by them. This makes a difference.. and i think you can do better.

**Comment by michaelmosmann** [comment]
@wilkinsona @snicoll beside all this .. i can also provide some spring specific stuff to make the integration easier.. feel free to ask.. we should reduce the api surface for this integration.. its mainly the mongodb version and the configuration class .. and as an result maybe some information about the running server port? .. and a way to stop it..  any suggestions? should we move this to an new issue?

**Comment by wilkinsona** [comment]
I've obviously come across badly here. Sorry. I didn't intend to insist on using your code in a certain way, but to understand the changes that have been made and the timing of those changes so that we can adapt accordingly.

We originally added support in Spring Boot 1.3 thanks to [a community contribution](https://github.com/spring-projects/spring-boot/pull/2002). I don't think we considered the impact that such integration may have on you and your project and we should have done. Spring Boot has a large user base and it's easy for us to forget the effect that exposing a project to that user base may have. Sorry for the lack of thought there.

A new issue about Spring integration sounds good to me. It may be that hosting the Spring (Boot) integration here would work out for the best in the long run. In figuring that out, I think we should optimise for whatever makes things easiest for you to maintain your project and to enjoy doing so.

**Comment by michaelmosmann** [comment]
@wilkinsona thank you:) .. as i think we aim for the same target we will find a solution that is for the benefit of all:)

**Comment by michaelmosmann** [comment]
.. i think, this is solved in many ways. please reopen, if any issues are left.
