### ISSUE TITLE
Firewall blocking download, help to use with a private registry or Jfrog Artifactory

### ISSUE THREAD

**Issue by Gmanweb** [flapdoodle-oss/de.flapdoodle.embed.mongo#389]
Hey

We are using de.flapdoodle.embed.mongo for a while on a Jenkins build VM and all was ok. We have since moved to a new Jenkins running on Kubernetes in a close environment that can only access JFrog Artifactory and private docker registry.

My question can de.flapdoodle.embed.mongo be configured to use JFrog artifactory and if so would there be any example we could follow for best practice.

**Comment by Killianoc** [comment]
Plus one for this issue, would be great to get a recommendation/solution.

**Comment by michaelmosmann** [comment]
@Gmanweb @Killianoc .. i just guess that you want to download the mongodb binaries from jfrog artifactory? .. or is there a problem with maven in resolving the de.flapdoodle.embed.mongo artifact from artifactory?

**Comment by robeatoz** [comment]
We had the same problem, and we uploaded the mongodb binaries from our local `$HOME/.embedmongo/linux` to JFrog as `Generic` `Package Type`.
Our Jenkins downloads the mongodb binaries from JFrog to `$HOME/.embedmongo/linux` before the build starts. `de.flapdoodle.embed.mongo` now doesn't need to download the binaries and continues with the build.

**Comment by michaelmosmann** [comment]
@Gmanweb @Killianoc you can change the download url (see https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo#customize-download-url)

**Comment by jcmillett** [comment]
I realize this is an old issue, but I figured I'd comment here rather than open a new ticket. I'm trying to use flapdoodle for integration tests in a spring boot 2.7.x app. However, our company uses zscaler and that appears to be blocking the download of mongodb when running the tests locally.

Looking through old issues it looked like manually downloading mongodb and storing it in `~/.embedmongo/osx` would make it so flapdoodle wouldn't try and download mongo, but that doesn't seem to work. When running the tests, I do see an error from flapdoodle, and it mentions downloading it manually and storing it in the `~/.embedmongo` directory, but the file path is very long and complex. Is it not possible to store the compressed mongo download in the `~/.embedmongo/<os_folder>` path anymore?

**Comment by michaelmosmann** [comment]
@jcmillett if you are using the more or less latest version of this library then there are some changes.. the long path you see is to avoid collisions and missconfigurations.. (its the download url as a hash) ... i think there is an error message with the download path and where to store it.. and if you download the artifact and put it in the wished location it should work as expected. .. 

if you have any trouble with that, just post your error message.. maybe there is some more trouble with that..  or the error message could be better (hmm.. now i have an idea how to improve the error message)..

You could also store the artifacts in a location where zscaler does not blocking it..
