### ISSUE TITLE
Unable to run embedded Mongo instance on CentOS Linux release 7.9.2009 (Core) machine - using Flapdoodle 3.4.8

### ISSUE THREAD

**Issue by briankurilko** [flapdoodle-oss/de.flapdoodle.embed.mongo#416]
I am trying to run an embedded MongoDB instance with version 4.2.13, using Flapdoodle version 3.4.8 to do so. When I try to run the tests on our CentOS Linux release 7.9.2009 (Core) machine, I receive the following error:
```
12:07:04  Download V4_2:Platform{operatingSystem=Linux, architecture=X86_64} DONE
12:07:04  Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.13.tgz START
12:07:04  Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.13.tgz extract mongodb-linux-x86_64-ubuntu1804-4.2.13/bin/mongod
12:07:04  Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.13.tgz nothing left
12:07:04  Extract /home/jenkins/.embedmongo/linux/mongodb-linux-x86_64-ubuntu1804-4.2.13.tgz DONE
12:07:04  [mongod error]/tmp/extract-29fba7e3-bcce-4a29-b537-3a9b6928a3a8extractmongod: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
12:07:04  [mongod error] 
12:07:18  [2022-07-27 16:07:16,618] ERROR [main]: mongo.InMemoryMongoPropertiesConfigurator -- Failed to create MongoClient for integration tests.
12:07:18  java.lang.RuntimeException: Could not start process: <EOF>
```
Does anyone know why this is happening?

**Comment by briankurilko** [comment]
Update on this: I followed [these instructions](https://github.com/flapdoodle-oss/de.flapdoodle.os#run) and added the system property `Linux|X86_64|CentOS|CentOS_7` to my program. I now get the following error:
```
4:07:11  [mongod output] Download V4_2:Platform{operatingSystem=Linux, architecture=X86_64, distribution=CentOS, version=CentOS_7} START
14:07:11  [2022-07-27 18:06:59,395] ERROR [main]: runtime.Starter -- prepare executable
14:07:11  java.io.IOException: Could not open inputStream for [https://fastdl.mongodb.org/tools/db/mongodb-database-tools-rhel70-x86_64-{tools.version}.tgz](https://fastdl.mongodb.org/tools/db/mongodb-database-tools-rhel70-x86_64-%7Btools.version%7D.tgz) with proxy Optional.empty
```

**Comment by michaelmosmann** [comment]
@briankurilko hmm.. looks like a bug.. the url looks wrong.

**Comment by vyu-talend** [comment]
Hello, I got the same issue, except for the error messages above. I found those messages might be helpful.
`[main] WARN de.flapdoodle.os.common.PeculiarityInspector - more than one match: [CentOS, Amazon]
[main] WARN de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder - because there is no package for PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
[main] WARN de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder - because there is no package for PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
Download PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64} START
[main] WARN de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder - because there is no package for PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}
[main] WARN de.flapdoodle.embed.mongo.packageresolver.linux.LinuxPackageFinder - because there is no package for PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64} we fall back to PRODUCTION:Platform{operatingSystem=Linux, architecture=X86_64, version=Ubuntu_20_04}`

**Comment by michaelmosmann** [comment]
@vyu-talend the os detection can not decide which os matches (could be CentOS or Amazon (just based on host names, because there is no other way to guess) .. you can override this with this system property: de.flapdoodle.os.override=Linux|X86_64|CentOS|CentOS_7 (choose the right version)

**Comment by vyu-talend** [comment]
@michaelmosmann Many thanks, I'll try it.

**Comment by vyu-talend** [comment]
> @vyu-talend the os detection can not decide which os matches (could be CentOS or Amazon (just based on host names, because there is no other way to guess) .. you can override this with this system property: de.flapdoodle.os.override=Linux|X86_64|CentOS|CentOS_7 (choose the right version)

It works. Thanks!

**Comment by michaelmosmann** [comment]
@vyu-talend .. i will make a new release where this situation is solved automatically ..(centos is used) so this workaround is not needed anymore (with this new release)

**Comment by michaelmosmann** [comment]
@briankurilko do you still have this problem?

**Comment by vyu-talend** [comment]
> @vyu-talend .. i will make a new release where this situation is solved automatically ..(centos is used) so this workaround is not needed anymore (with this new release)

Thanks, Michael! Good to hear that!

**Comment by michaelmosmann** [comment]
new release is done.. should be in maven central in about 12-24hrs

**Comment by michaelmosmann** [comment]
@vyu-talend can you test this with this new release an close this issue if everything is fine? thanks:)

**Comment by michaelmosmann** [comment]
@vyu-talend no problem with that.. :)
