### ISSUE TITLE
Please Support MongoDB 6.0.8

### ISSUE THREAD

**Issue by XSpielinbox** [flapdoodle-oss/de.flapdoodle.embed.mongo#472]
When setting `de.flapdoodle.mongodb.embedded.version=6.0.8` in my `applications.properties` trying to run the tests results in the following error:
`Caused by: java.lang.IllegalArgumentException: could not resolve package for GenericFeatureAwareVersion{6.0.8}:Platform{operatingSystem=Linux, architecture=X86_64, distribution=CentOS, version=CentOS_9}
`
I suspect this is because the definition for version 6.0.8 is missing from [Versions.java](https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo/blob/main/src/main/java/de/flapdoodle/embed/mongo/distribution/Version.java#L251).

**Comment by michaelmosmann** [comment]
@XSpielinbox it is a little bit more complicated.. its missing here: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver .. but i will add the latest batch of releases so that 6.0.8 is included..

**Comment by michaelmosmann** [comment]
@XSpielinbox because mongodb decided some time ago that the do not release a new version for every platform, that the download paths don't follow a common naming schema and that there is not a distribution for linux anymore .. but for ubuntu, redhat, ... 

this is how it started: https://github.com/michaelmosmann/embedmongo.flapdoodle.de/blob/5bb2f6596c8051cf4df1b7cf07b6e5d75fc2a479/src/main/java/de/flapdoodle/embedmongo/Paths.java .. but this stopped working some years ago

**Comment by michaelmosmann** [comment]
@XSpielinbox .. ah.. now i understand why you think 2) could work.. in the old days it worked this way if you used spring because they bypassed my version enum you could use in your code..  but as there are different download paths for different versions of the same os this will not work..

have a look at the mac-os part: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/main/src/test/resources/de/flapdoodle/embed/mongo/packageresolver/explainedSnapshot.txt

i wish it would be easier than that.. :)

**Comment by michaelmosmann** [comment]
@XSpielinbox .. but maybe i have an idea how to automate this a little bit more..

**Comment by michaelmosmann** [comment]
@XSpielinbox there is a new release .. and i did automate this a little bit more.. :) thanks for the idea..

**Comment by michaelmosmann** [comment]
@XSpielinbox debian rule for 6.0.7: https://github.com/flapdoodle-oss/de.flapdoodle.embed.mongo.packageresolver/blob/1eab61f67624be49d6e9c480157373c684caeaee/src/main/java/de/flapdoodle/embed/mongo/packageresolver/linux/DebianPackageFinder.java#L80 ..

what i did change: As before i aggregate all version information from snapshots of the download-page .. what i did change was that before i created a dump of this version information and made the changes by hand.. now i render the java code for the implementation for these version information. I do not use these generated files directly (that's a next step), but the generated files contains now everything .. as i changed them by hand i missed some changes and it was much more time consuming.

from now on it is very easy to see if there is something new an regenerate the rules from that..
