### ISSUE TITLE
Move to slf4j API with log4j

### ISSUE THREAD

**Issue by igreenfield** [flapdoodle-oss/de.flapdoodle.embed.mongo#67]
Could you move the code to use slf4j API and log4j instead of java.util.logging?
I can do that if you give me permission to commit changes.

**Comment by jirutka** [comment]
Slf4j serves as a simple facade or abstraction for various logging frameworks (e.g. java.util.logging, logback, log4j) allowing the end user to plug in the desired logging framework at _deployment_ time.

It’s a tiny JAR (31.4 kB) with no dependencies. How it can make harder for other people to integrate it? This is nonsense. Using JUL (java.util.logging) makes integration to other projects much harder, because it can’t be effectively integrated with any other logging backend (read [here](http://www.slf4j.org/legacy.html#jul-to-slf4j)). JUL should not be used anywhere, it’s plain wrong.

**Comment by michaelmosmann** [comment]
Beside this funny bashing: So do you want this change?

**Comment by jirutka** [comment]
Yeah, of course, I wouldn’t have written it if not…

**Comment by matlockx** [comment]
@jirutka May I ask you kindly for a pr?

**Comment by matlockx** [comment]
It's not that Michael and I don't want to do it but we are both currently heavily involved in some projects and I don't know when we start writing on it so I was wondering whether it's possible for you to work on it?  We would be very grateful

**Comment by jirutka** [comment]
@matlockx Sure, here it is: #113 and https://github.com/flapdoodle-oss/de.flapdoodle.embed.process/pull/22.
